diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=luckj
user.email=luckjjh1@naver.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=https://github.com/luckjjh/modifyH-java-racingcar-precourse.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=utcStudy
branch.main.merge=refs/heads/main
remote.utcStudy.url=https://github.com/UTC-precourse/modifyH-java-racingcar-precourse.git
remote.utcStudy.fetch=+refs/heads/*:refs/remotes/utcStudy/*
